docs:
  - changed-files:
      - any-glob-to-all-files:
          - "**/*.md"
          - "docs/**/*"

test:
  - changed-files:
      - any-glob-to-all-files:
          - "**/test/**/*.dart"

chore:
  - changed-files:
      - any-glob-to-all-files:
          - ".*"
          - "**.yaml"
          - "*.gemfile"
          - "**.json*"

ci:
  - changed-files:
    - all-globs-to-any-file:
      - ".github/**/*"
      - "!.github/**/*.md"

check:
  - changed-files:
    - all-globs-to-any-file:
      - "packages/**/*.dart"
      - "!packages/entity/**/*"
      - "!packages/**/test/**/*"
      - "!packages/**/*.g.dart"
