docs:
  - changed-files:
      - any-glob-to-all-files:
          - "**/*.md"
          - "docs/**/*"

test:
  - changed-files:
      - any-glob-to-all-files:
          - "**/test/**/*"

chore:
  - changed-files:
      - any-glob-to-all-files:
          - "*"
          - ".*"
          - "*.*"
          - "**/*.sh"
          - ".husky/**/*"
          - ".idea/**/*"
          - ".vscode/**/*"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"
