- name: "docs"
  color: "F6E100"
  description: "Area: docs"
- name: "test"
  color: "F6E100"
  description: "Area: test"
- name: "ci"
  color: "F6E100"
  description: "Area: CI"
- name: "chore"
  color: "F6E100"
  description: "Area: other"
