docs:
  - changed-files:
      - any-glob-to-all-files:
          - "**/*.md"
          - "docs/**/*"

test:
  - changed-files:
      - any-glob-to-all-files:
          - "**/test/**/*.dart"

chore:
  - changed-files:
      - any-glob-to-all-files:
          - ".*"
          - "**.yaml"
          - "*.gemfile"
          - "**.json*"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"

check:
- changed-files:
  - any-glob-to-any-file:
    - "packages/**/*.dart"
  - all-globs-to-all-files:
    - "!packages/entity/**/*"
    - "!packages/**/test/**/*"
    - "!packages/**/*.g.dart"
    - "!packages/**/*.md"
