docs:
  - changed-files:
      - any-glob-to-all-files:
          - "**/*.md"
          - "docs/**/*"
      - all-globs-to-all-files:
          - "!.github/**/*"

test:
  - changed-files:
      - any-glob-to-all-files:
          - "**/test/**/*.dart"

chore:
  - changed-files:
      - any-glob-to-all-files:
          - ".*"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"
