docs:
  - changed-files:
      - any-glob-to-all-files:
          - "**/*.md"
          - "docs/**/*"

test:
  - changed-files:
      - any-glob-to-all-files:
          - "**/test/**/*.dart"

chore:
  - changed-files:
      - any-glob-to-all-files:
          - ".*"
          - "*.yaml"
          - "*.gemfile"

ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"
