name: Prepare for review

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  label-area:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Add alea label
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yaml
          sync-labels: true
